import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarCheck, Check, Clock3, Globe2, MessageCircle, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'
import { supabase, isSupabaseConfigured } from '../lib/supabaseClient'
import { getLocale, t } from '../lib/i18n'
import { getVerticalProfile, normalizeVertical } from '../lib/tenant'

const FALLBACK_PLANS = [{ codigo: 'starter', nombre: 'Starter', descripcion: 'Agenda, clientes y reservas online', precio_mensual: 19, moneda: 'USD', trial_dias: 14 }, { codigo: 'pro', nombre: 'Pro', descripcion: 'Automatizaciones, WhatsApp y métricas avanzadas', precio_mensual: 39, moneda: 'USD', trial_dias: 14 }, { codigo: 'business', nombre: 'Business', descripcion: 'Operación multi-sede y soporte prioritario', precio_mensual: 79, moneda: 'USD', trial_dias: 14 }]

const BENEFITS = [{ icon: CalendarCheck, title: 'Reservas online', text: 'Horarios disponibles en tiempo real, duración por servicio y sin superposiciones.' }, { icon: UsersRound, title: 'Clientes y equipo', text: 'Centralizá fichas, colaboradores, servicios y horarios de trabajo.' }, { icon: MessageCircle, title: 'Automatizaciones', text: 'Prepará WhatsApp y recordatorios con controles y aprobación humana.' }, { icon: Globe2, title: 'Adaptable a tu rubro', text: 'El mismo núcleo para barberías, peluquerías, estética, tattoo y más.' }]

export default function Landing({ vertical = 'custom' }) {
  const locale = getLocale()
  const [plans, setPlans] = useState(FALLBACK_PLANS)
  const profile = useMemo(() => getVerticalProfile(normalizeVertical(vertical)), [vertical])
  useEffect(() => { if (isSupabaseConfigured) supabase.rpc('get_public_saas_catalog').then(({ data }) => { if (Array.isArray(data) && data.length) setPlans(data) }) }, [])
  useEffect(() => { document.title = `${t('product', locale)} — ${profile.label}` }, [locale, profile.label])
  return <main className="landing-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: t('product', locale), applicationCategory: 'BusinessApplication', operatingSystem: 'Web', offers: { '@type': 'Offer', price: 0, priceCurrency: 'USD', description: 'Prueba gratuita de 14 días' } }) }} />
    <nav className="landing-nav"><a className="landing-brand" href="/"><span className="landing-brand-mark">A</span><span>{t('product', locale)}</span></a><div className="landing-nav-actions"><a href="#planes">Planes</a><a href="/demo">Demo aislada</a><a href="/ingresar">{t('login', locale)}</a><a className="landing-nav-cta" href="/registro">{t('trial', locale)} <ArrowRight size={15} /></a></div></nav>
    <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-eyebrow"><Sparkles size={14} /> {t('eyebrow', locale)}</span><h1>{profile.label !== 'Otro' ? `${profile.label}: ` : ''}{t('title', locale)}</h1><p>{t('description', locale)}</p><div className="landing-actions"><a className="landing-button primary" href="/registro">{t('trial', locale)} <ArrowRight size={16} /></a><a className="landing-button secondary" href="/demo">Probar demo aislada</a></div><div className="landing-trust"><ShieldCheck size={15} /> Sin tarjeta · Datos aislados por negocio · Podés cancelar</div></div><div className="landing-preview" aria-label="Vista ilustrativa del producto"><div className="landing-preview-top"><span /><span /><span /></div><div className="landing-preview-grid"><div><small>Agenda</small><strong>Ejemplo</strong><div className="landing-bars"><i /><i /><i /><i /></div></div><div><small>Reservas online</small><strong>Demo</strong><div className="landing-line" /></div><div className="landing-preview-calendar"><small>Agenda ficticia</small>{['09:00 Corte', '10:30 Barba', '12:00 Combo', '15:00 Color'].map((item) => <span key={item}><Clock3 size={11} /> {item}</span>)}</div></div></div></section>
    <section className="landing-section"><p className="landing-section-kicker">{t('benefits', locale)}</p><div className="landing-benefits">{BENEFITS.map(({ icon: Icon, title, text: description }) => <article key={title}><span className="landing-icon"><Icon size={20} /></span><h2>{title}</h2><p>{description}</p></article>)}</div></section>
    <section id="como-funciona" className="landing-section landing-steps"><p className="landing-section-kicker">{t('steps', locale)}</p><div className="landing-step-grid"><article><b>01</b><h2>Registrate</h2><p>Creá tu cuenta con nombre, email y contraseña. Verificás tu correo y listo.</p></article><article><b>02</b><h2>Configurá tu negocio</h2><p>Elegí rubro, idioma, zona horaria, servicios, colaboradores y marca.</p></article><article><b>03</b><h2>Empezá a recibir reservas</h2><p>Publicá tu página de reservas y mejorá la operación desde un solo panel.</p></article></div></section>
    <section id="planes" className="landing-section"><p className="landing-section-kicker">{t('plans', locale)}</p><div className="landing-plans">{plans.map((plan) => <article className="landing-plan" key={plan.codigo}><h2>{plan.nombre}</h2><p>{plan.descripcion}</p><strong>{Number(plan.precio_mensual) === 0 ? 'Personalizado' : `${plan.moneda} ${Number(plan.precio_mensual).toLocaleString(locale)}`}<small>/mes</small></strong><ul><li><Check size={14} /> Prueba de {plan.trial_dias || 14} días</li><li><Check size={14} /> Agenda y reservas públicas</li><li><Check size={14} /> Soporte para configurar tu negocio</li></ul><a className="landing-button secondary" href="/registro">Empezar</a></article>)}</div></section>
    <section className="landing-faq landing-section"><p className="landing-section-kicker">{t('faq', locale)}</p><details open><summary>¿Puedo empezar sin configurar WhatsApp?</summary><p>Sí. La agenda y las reservas funcionan de forma independiente. WhatsApp se conecta después, con una configuración adicional.</p></details><details><summary>¿Puedo usarlo en otro rubro?</summary><p>Sí. El producto separa el núcleo de agenda y clientes del contenido específico de cada vertical.</p></details><details><summary>¿Se crean datos ficticios?</summary><p>No. El onboarding crea sólo la configuración mínima y no inventa empleados ni clientes.</p></details></section>
    <section className="landing-cta"><h2>{t('contact', locale)}</h2><p>Podés empezar la prueba o escribirnos para revisar si el producto encaja con tu operación.</p><a className="landing-button primary" href="/registro">Crear mi cuenta <ArrowRight size={16} /></a><small>{t('footer', locale)}</small></section>
    <footer className="landing-footer"><span>© {new Date().getFullYear()} Austral Automatizaciones</span><div><a href="/registro">Registro</a><a href="/ingresar">Ingresar</a><a href="#planes">Planes</a></div></footer>
  </main>
}
