import { useEffect, useState } from 'react'
import { Bell, Check, Plus, RefreshCw, X } from 'lucide-react'
import { supabase } from '../lib/supabaseClient'
import { EmptyState } from './ui'

const INITIAL = { lead_id: '', titulo: '', notas: '', prioridad: 'normal', vence_at: '' }
const fmt = (value) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Sin vencimiento'

export default function CRMActionInbox({ role = 'owner' }) {
  const [actions, setActions] = useState([]); const [leads, setLeads] = useState([]); const [form, setForm] = useState(INITIAL); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [completingId, setCompletingId] = useState(null); const [error, setError] = useState(''); const canWrite = ['owner', 'admin', 'sales', 'automation'].includes(role)
  const load = async () => { setLoading(true); const [a, l] = await Promise.all([supabase.from('crm_acciones').select('id,lead_id,titulo,notas,prioridad,estado,vence_at,recordatorio_at,crm_leads(nombre_contacto,crm_negocios(nombre))').eq('estado', 'pending').order('vence_at', { ascending: true, nullsFirst: false }), supabase.from('crm_leads').select('id,nombre_contacto,crm_negocios(nombre)').neq('pipeline_stage', 'do_not_contact').order('updated_at', { ascending: false }).limit(200)]); if (a.error || l.error) setError(a.error?.message || l.error?.message || 'No se pudieron cargar las acciones'); else { setError(''); setActions(a.data || []); setLeads(l.data || []) } setLoading(false) }
  useEffect(() => { load() }, [])
  const save = async (event) => { event.preventDefault(); if (saving) return; setSaving(true); try { const { error: saveError } = await supabase.from('crm_acciones').insert({ lead_id: Number(form.lead_id), titulo: form.titulo.trim(), notas: form.notas.trim() || null, prioridad: form.prioridad, vence_at: form.vence_at ? new Date(form.vence_at).toISOString() : null, recordatorio_at: form.vence_at ? new Date(form.vence_at).toISOString() : null, created_by: (await supabase.auth.getUser()).data.user?.id }); if (saveError) setError(saveError.message); else { setOpen(false); setForm(INITIAL); await load() } } finally { setSaving(false) } }
  const complete = async (action) => { if (completingId) return; setCompletingId(action.id); try { const { error: updateError } = await supabase.from('crm_acciones').update({ estado: 'completed', completed_at: new Date().toISOString() }).eq('id', action.id); if (updateError) setError(updateError.message); else await load() } finally { setCompletingId(null) } }
  return (
    <div className="crm-actions-page">
      <div className="panel-header-inline"><div><h2 className="panel-title"><Bell size={16} /> Seguimientos internos</h2><p className="panel-subtitle">Alertas dentro del panel. No se envían notificaciones externas.</p></div><div className="page-actions"><button className="btn" onClick={load} disabled={loading || saving || Boolean(completingId)}><RefreshCw size={14} /> Actualizar</button>{canWrite && <button className="btn btn-primary" onClick={() => setOpen(true)} disabled={saving}><Plus size={14} /> Nueva acción</button>}</div></div>
      {error && <div className="error-banner" role="alert">{error}</div>}
      {loading ? <div role="status" aria-live="polite"><EmptyState description="Cargando acciones..." /></div> : actions.length === 0 ? <EmptyState description="No hay seguimientos pendientes." /> : <div className="crm-action-list">{actions.map((action) => <article className={`crm-action-row ${action.vence_at && new Date(action.vence_at) < new Date() ? 'overdue' : ''}`} key={action.id}><div><strong>{action.titulo}</strong><small>{action.crm_leads?.nombre_contacto || 'Lead'} · {action.crm_leads?.crm_negocios?.nombre || 'Negocio'} · {action.prioridad}</small>{action.notas && <p>{action.notas}</p>}</div><div><span>{fmt(action.vence_at)}</span>{canWrite && <button className="btn" onClick={() => complete(action)} disabled={Boolean(completingId)}><Check size={14} /> {completingId === action.id ? 'Completando…' : 'Completar'}</button>}</div></article>)}</div>}
      {open && <div className="modal-overlay" onClick={() => { if (!saving) setOpen(false) }}><form className="modal-box action-form" onSubmit={save} onClick={(event) => event.stopPropagation()} aria-busy={saving}><div className="modal-header"><div><h2 className="panel-title">Nueva acción</h2><p className="panel-subtitle">Sólo recordatorio interno.</p></div><button className="btn-icon-plain" type="button" onClick={() => setOpen(false)} aria-label="Cerrar" disabled={saving}><X size={18} /></button></div><label className="modal-label">Lead<select className="text-input" required value={form.lead_id} onChange={(event) => setForm({ ...form, lead_id: event.target.value })} disabled={saving}><option value="">Elegí un lead</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.nombre_contacto || `Lead #${lead.id}`} · {lead.crm_negocios?.nombre || ''}</option>)}</select></label><label className="modal-label">Título<input className="text-input" required maxLength="160" value={form.titulo} onChange={(event) => setForm({ ...form, titulo: event.target.value })} disabled={saving} /></label><div className="modal-row"><label className="modal-label">Prioridad<select className="text-input" value={form.prioridad} onChange={(event) => setForm({ ...form, prioridad: event.target.value })} disabled={saving}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className="modal-label">Vence<input className="text-input" type="datetime-local" value={form.vence_at} onChange={(event) => setForm({ ...form, vence_at: event.target.value })} disabled={saving} /></label></div><label className="modal-label">Notas<textarea className="text-input" rows="3" value={form.notas} onChange={(event) => setForm({ ...form, notas: event.target.value })} disabled={saving} /></label><div className="modal-actions"><button className="btn" type="button" onClick={() => setOpen(false)} disabled={saving}>Cancelar</button><button className="btn btn-primary" type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar acción'}</button></div></form></div>}
    </div>
  )
}
